name: Build

on: 
  # pull:
  #   branches: [main]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: latest
          dest: build
          prefix: discord-qqmusic-rpc
          targets: windows/amd64,windows/386
          # targets: windows/amd64,windows/386,linux/amd64,darwin/amd64,darwin/arm64
          v: true
          x: true
          race: false
          ldflags: -H=windowsgui -s -w
          buildmode: default
          trimpath: true
          working_dir: ./
          
      - name: Run UPX
        uses: crazy-max/ghaction-upx@v2
        with:
          version: latest
          files: |
            build/*.exe
          args: --best

      - uses: actions/upload-artifact@v3
        with:
          name: discord-qqmusic-rpc_386
          path: build/discord-qqmusic-rpc-windows-386.exe

      - uses: actions/upload-artifact@v3
        with:
          name: discord-qqmusic-rpc_amd64
          path: build/discord-qqmusic-rpc-windows-amd64.exe